version: "3.8"

services:
  mysql_db:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "esprithub"
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - my_shared_network

  app:
    build: ..
    depends_on:
      - mysql_db
    restart: on-failure
    ports:
      - "8082:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysql_db:3306/esprithub?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC",
        "spring.datasource.username": "root",
        "spring.datasource.password": "",
        "spring.jpa.show-sql": "true",
        "spring.jpa.hibernate.ddl-auto": "update",
        "server.servlet.context-path": "/projectARCTIC3",
        "server.port": "8089",
        "management.endpoints.web.exposure.include": "*",
        "management.endpoint.prometheus.enabled": "true",
        "management.endpoints.web.base-path": "/actuator",
        "management.server.port": "8089",
        "management.server.base-path": "/projectARCTIC3"
      }'
    volumes:
      - .m2:/root/.m2
      - .:/workdir/server/src
      - ./src/main/resources/application.yml:/workdir/server/src/main/resources/application.yml
    stdin_open: true
    tty: true
    networks:
      - my_shared_network

volumes:
  db:

networks:
  my_shared_network:
    external: true
