global:
  scrape_interval: 15s

scrape_configs:
  # Scraping Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # Prometheus itself

  - job_name: "project_app"
    metrics_path: "/projectARCTIC3/actuator/prometheus"
    static_configs:
      - targets: ["app:8089"]  # Changed to match the service name in docker-compose
    scrape_interval: 5s
